### ISSUE TITLE
Calcuate the final score

### ISSUE THREAD

**Issue by whelblin** [whelblin/Gamma#17]
The final score should be displayed on death and should be the score counter multiplied by the time

**Comment by Jhoope11** [comment]
There should be a function that would calculate final score, it isn't tested tho

**Comment by justramle** [comment]
I completed the update calculate the best score/ final score after death. 
I created another var bestscore next to score. Then whenever player hit asteroids and scored inMenu, it will also update bestScore as well.
Then I print BestScore at resetGame(). 
Do you mind to test it out for me on tramFrontEnd branch to see if it works?
