### ISSUE TITLE
Asteroids Game

### ISSUE THREAD

**Issue by whelblin** [whelblin/Gamma#3]
You have a ship that must dodge and shoot asteroids. I was thinking of a rouge-like game similar to Vampire Survivors. So you gain experience for every asteroid you destroy and after so many, you get to pick a power-up. It can be movement speed, bullet damage, bullet speed, fire rate, or body health. We could also add special power-ups like a bigger cannon. The goal is to survive as long as possible.

**Comment by justramle** [comment]
I like your idea so I added my label to this idea as a vote. We could also make it more fun by designing the shooting 3D stars/asteroids in starfield with more depth and speeds by moving mouse and the shooter can move the mouse along to shoot the target.
