### ISSUE TITLE
level up screen pops up when you level up

### ISSUE THREAD

**Issue by whelblin** [whelblin/Gamma#34]
click the screen for it to go away

**Comment by Jhoope11** [comment]
Needs a pause game function to freeze the game upon level up, Then need to figure out how the pop up will work

**Comment by Jhoope11** [comment]
Game can be paused and unpaused with esc

**Comment by justramle** [comment]
Tested successfully:
 - level up box appear when exp bar completed
 - use to unpause and pause working
