### ISSUE TITLE
Movement

### ISSUE THREAD

**Issue by whelblin** [whelblin/Gamma#7]
The WASD and the arrows keys should move the player in the corresponding direction

**Comment by Jhoope11** [comment]
The yin here works for a basic wasd movement. We need to modify it so it will work with the p5play.js sprite class.

**Comment by Jhoope11** [comment]
4d movement is added and working, need to figure out 8d movement.

**Comment by Jhoope11** [comment]
Full movement is now implemented in the playerstuff branch
